# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default=b'I really like Python and Django'),
        ),
    ]
